apiVersion: v1
kind: Service
metadata:
  name: config-reloader-service
  namespace: config-hot-reloader
spec:
  type: ClusterIP
  selector:
    app: config-reloader
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
